Repository MLH-Fellowship/LATAM-C-Turtles-Portfolio, pull requests merged in 2021-06, with the labels that each got.

#4 Create pull_request_template.md
  pull_request_template.md
Labels: documentation

#11 Create landing page
  app/static/css/main.css
  app/static/img/Carlos.png
  app/static/img/Jorge.png
  app/static/img/MLH_Logo.svg
  app/static/img/Saul.png
  app/static/img/Team.png
  app/static/img/Turtle1.png
  app/static/img/Turtle2.png
  app/static/img/Turtle3.png
  app/templates/base.html
  app/templates/index.html
Labels: enhancement

#17 Create Footer
  app/static/css/footer.css
  app/templates/base.html
  app/templates/landing_page.html
Labels: enhancement

#19 Fix Land Page Styling
  app/static/css/main.css
  app/static/img/wave.png
  app/templates/landing_page.html
Labels: bug, enhancement

#23 Update Readme
  README.md
  images/-LinkedIn-black.svg
  images/Contributors.svg
  images/figma-design.png
  images/issues.svg
  images/issues2.svg
Labels: documentation

#24 009 create profile
  .gitignore
  app/__init__.py
  app/static/css/profile.css
  app/static/data/saul.json
  app/static/img/bookworms.jpg
  app/static/img/github-icon.png
  app/static/img/mlh_fellowship.jpg
  app/static/img/profile-saul.png
  app/static/img/react.jpeg
  app/static/img/studybuddies.png
  app/static/img/tec.png
  app/static/js/profile.js
  app/templates/base.html
  app/templates/profile.html
Labels: enhancement

#25 008 create homepage
  app/__pycache__/__init__.cpython-39.pyc
  app/static/css/main.css
  app/static/img/airport.png
  app/static/img/beach-ball.jpg
  app/static/img/codelines.png
  app/static/img/commits.png
  app/static/img/github.png
  app/static/img/office.png
  app/static/img/pr.png
  app/static/img/rocket.png
  app/static/img/world.png
  app/static/img/world2.png
  app/static/js/main.js
  app/templates/landing_page.html
Labels: enhancement

#28 026 fix homepage
  app/__pycache__/__init__.cpython-39.pyc
  app/static/css/footer.css
  app/static/css/main.css
  app/templates/landing_page.html
Labels: bug, enhancement
